# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec for FileReach — cross-platform (Windows / macOS / Linux).

Build with:   pyinstaller filereach.spec --noconfirm
Produces:     dist/FileReach/  (a portable one-folder distribution)

Notes:
  * The UI (static/) is bundled via datas and located at runtime via sys._MEIPASS.
  * On Windows, uac_admin=True embeds a manifest that requests Administrator on
    launch — that is the SINGLE permission prompt the user ever sees.
  * Optional deps (rapidfuzz, pytesseract) are listed as hidden imports so they
    bundle when present; if absent at runtime the engine falls back gracefully.
"""
import os

block_cipher = None

# Optional per-platform icon (generated by make_icon.py in CI / locally)
icon_path = None
if os.path.exists("assets/icon.ico") and os.name == "nt":
    icon_path = "assets/icon.ico"
elif os.path.exists("assets/icon.icns") and os.path.exists("assets/icon.icns"):
    icon_path = "assets/icon.icns"

a = Analysis(
    ["app.py"],
    pathex=[],
    binaries=[],
    datas=[("static", "static")],
    hiddenimports=[
        "PIL",
        "rapidfuzz",
        "rapidfuzz.fuzz",
        "pytesseract",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["tkinter", "matplotlib", "numpy", "PyQt5", "PySide2"],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe_kwargs = dict(
    console=True,
    name="FileReach",
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
if icon_path:
    exe_kwargs["icon"] = icon_path
if os.name == "nt":
    # Windows: request elevation once via the embedded application manifest.
    exe_kwargs["uac_admin"] = True

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    **exe_kwargs,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="FileReach",
)
